pytrade/apps/backend/urls.py
from django.conf.urls import patterns, url, include


urlpatterns = patterns(
    'pytrade.apps.backend.views',
    url(r'^$', 'index_view', name='vista_backend'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^exportar/$', 'paquete_exportar_view', name='vista_exportar_paquete'),
    url(r'^busqueda/(?P<tipo>.*)/$', 'cliente_busqueda_view', name='vista_busqueda_clientes'),
    url(r'^cliente/$', 'cliente_list_view', name='vista_lista_clientes'),
    url(r'^cliente/(?P<user>.*)/$', 'cliente_historial_view', name='vista_historial_cliente'),
    url(r'^paquete/$', 'paquete_list_view', name='vista_lista_paquetes'),
    url(r'^paquete/agrupar/$', 'paquete_agrupar_list', name='vista_agrupar_paquetes'),
    url(r'^paquete/agregar/$', 'paquete_agregar_view', name='vista_paquete_agregar'),
    url(r'^paquete/editar/(?P<id>.*)/$', 'paquete_editar_view', name='vista_paquete_editar'),
    url(r'^paquete/entregar/(?P<user>.*)/$', 'paquete_entregar_view', name='vista_entregar_paquete'),
    url(r'^paquete/wsentregar$', 'wspaquete_entregar_view', name='ws_entregar_paquete'),
    url(r'^mail/$', 'enviar_mail_view', name='vista_enviar_mail'),
    url(r'^compra/$', 'compra_list_view', name='vista_lista_compras'),
    url(r'^compra/agregar$', 'compra_agregar_view', name='vista_agregar_orden_compra'),
    url(r'^compra/cotizar/(?P<id>.*)/$', 'compra_cotizar_view', name='vista_cotizar_pedido'),
    url(r'^compra/pagar/(?P<id>.*)/$', 'compra_pagar_pedido_view', name='vista_pagar_pedido'),
    (r'^barcode/(?P<paquete>.*)/$', 'barcode_view'),
    url(r'^listado/$', 'generar_listado_mail_view', name='vista_generar_listado'),
    url(r'^carga/importar/$', 'carga_importar_view', name='vista_importar_carga'),
    url(r'^carga/$', 'carga_list_view', name='vista_lista_cargas'),
    url(r'^carga/(?P<id>.*)/$', 'carga_detalle_view', name='vista_detalle_carga'),
    url(r'^ticket/$', 'ticket_list_view', name='vista_lista_tickets'),
    url(r'^ticket/estado/$', 'ticket_cambio_estado_view', name='vista_cambio_estado_ticket'),
    url(r'^ticket/(?P<id>.*)/$', 'ticket_detalle_view', name='vista_detalle_ticket'),
    url(r'^proveedor/$', 'proveedor_abm_view', name='vista_agregar_proveedor'),
    url(r'^proveedor/(?P<id>.*)/$', 'proveedor_abm_view', name='vista_editar_proveedor'),
    #caja
    url(r'^caja/$', 'caja_list_view', name='vista_lista_caja'),
    url(r'^caja/apertura/$', 'caja_apertura_view', name='vista_apertura_caja'),
    url(r'^caja/egreso/$', 'caja_egreso_abm_view', name='vista_agregar_egreso'),
    url(r'^caja/abierta/$', 'caja_abierta_view', name='vista_caja_abierta'),
    url(r'^caja/cierre/(?P<id>.*)/$', 'caja_cierre_view', name='vista_cierre_caja'),
    url(r'^caja/(?P<id>.*)/$', 'caja_detalle_view', name='vista_detalle_caja'),
    #manifiesto
    url(r'^manifiesto/$', 'manifiesto_list_view', name='vista_lista_manifiesto'),
    url(r'^manifiesto/agregar$', 'manifiesto_agregar_view', name='vista_manifiesto_agregar'),
    url(r'^manifiesto/(?P<id>.*)/$', 'manifiesto_detalle_view', name='vista_detalle_manifiesto'),
    #factura
    url(r'^factura/(?P<factura_id>.*)/$', 'factura_detalle_view', name='vista_detalle_factura'),
    url(r'^facturacliente/(?P<ticket_id>.*)/$', 'factura_cliente_view', name='vista_factura_cliente'),
    #webservices
    url(r'^webservices/ws_motivo_egreso', 'wsmotivo_egreso_view', name='ws_motivo_egreso'),
    url(r'^webservices/ws_compra_divisa', 'wscompra_divisa_view', name='ws_compra_divisa'),
    url(r'^webservices/ws_detalle_compra_guardar', 'wsdetalle_compra_guardar_view', name='ws_guardar_detalle_compra'),
    url(r'^webservices/ws_ticket_estado', 'wsticket_cambio_estado_view', name='ws_ticket_cambio_estado'),
    url(r'^webservices/ws_manifiesto_paquetes', 'wsmanifiesto_paquetes_view', name='ws_manifiesto_paquetes'),
    url(r'^webservices/ws_cliente_factura', 'wsfactura_cliente_view', name='ws_manifiesto_paquetes'),
    #reportes
    url(r'^informe/1', 'i_cargas_cliente_view', name='i_cargas_cliente'),
    url(r'^informe/2', 'i_ingresos_egresos_view', name='i_ingresos_egresos'),
)

pytrade/apps/home/urls.py
from django.conf.urls import patterns, url
#from pytrade.apps.home.views import wsagregar_prepaquete
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = patterns(
    'pytrade.apps.home.views',
    url(r'^$', 'index_view', name='vista_inicio'),
    url(r'^login/', 'login_view', name='vista_login'),
    url(r'^logout/', 'logout_view', name='vista_logout'),
    url(r'^registrar/', 'registrar_view', name='vista_registrar'),
    # Perfiles
    url(r'^profile/$', 'profile_view', name='vista_profile'),
    url(r'^profile/edit/', 'perfil_usuario_view', name='vista_perfil'),
    url(r'^profile/comprar/', 'comprar_view', name='vista_comprar'),
    url(r'^profile/historial/', 'cliente_historial_view', name='vista_historial'),
    # Paginas Internas
    url(r'^empresa/', 'empresa_view', name='vista_empresa'),
    url(r'^servicio/', 'servicio_view', name='vista_servicio'),
    url(r'^tarifa/', 'tarifa_view', name='vista_tarifa'),
    url(r'^preguntas/', 'preguntas_view', name='vista_preguntas'),
    url(r'^tiendas/', 'tiendas_view', name='vista_tiendas'),
    url(r'^contacto/', 'contacto_view', name='vista_contacto'),
    #webservices
    url(r'^webservices/ws_email', 'wsemail_view', name='ws_email'),
    url(r'^webservices/ws_codigo', 'wscodigo_view', name='ws_codigo'),
    #RESTful
    #url(r'^ws/paquete/$', wsagregar_prepaquete.as_view(), name='vista_rest_agregar_prepaquete'),
)

#urlpatterns = format_suffix_patterns(urlpatterns)

pytrade/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('pytrade.apps.home.urls')),
    url(r'^backend/', include('pytrade.apps.backend.urls')),
    url(r'^recuperar/', include('password_reset.urls')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

#urlpatterns = format_suffix_patterns(urlpatterns)

pytrade/apps/backend/models.py
#encoding=utf8
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.db.models import Sum
from decimal import Decimal
#import django_filters


class Configuracion(models.Model):
    dolar = models.IntegerField()
    ultimo_valor = models.IntegerField()
    monto_minimo = models.IntegerField()
    comision = models.IntegerField(default=10)

    def __unicode__(self):
        return "Dolar=%s|Ult. Valor=%s|Monto=%s" % (self.dolar, self.ultimo_valor, self.monto_minimo)

    class Meta:
        db_table = 'pytrade_config'
        verbose_name_plural = "configuraciones"


class Moneda(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=10)
    cotizacion = models.IntegerField()

    def __unicode__(self):
        return self.codigo

    def natural_key(self):
        return self.codigo

    class Meta:
        db_table = 'pytrade_moneda'


# class Empresa(models.Model):
#     nombre = models.CharField(max_length=100)
#     codigo = models.CharField(max_length=100)
#     mail = models.EmailField(null=True, blank=True)
#
#     def __unicode__(self):
#         return "%s - %s" % (self.nombre, self.codigo)
#
#     class Meta:
#         db_table = 'pytrade_empresas'


class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    url = models.URLField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = 'pytrade_proveedor'
        verbose_name_plural = "proveedores"


class FormaPago(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=15)
    comision = models.IntegerField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = 'pytrade_formapago'


class Compra(models.Model):
    user = models.ForeignKey(User)
    detalle = models.ManyToManyField('CompraDetalle', blank=True, null=True)
    pago = models.ManyToManyField('Pago', blank=True, null=True)
    valor_compra_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)  # Suma Detalle Dolares
    valor_compra_gs = models.BigIntegerField(blank=True, null=True)  # Suma Detalle Guaranies
    comision_dolar = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Configuracion.comision/100
    comision_gs = models.BigIntegerField(null=True, blank=True)
    # Por Admin cuando el Cliente Paga Completamente
    pagado = models.BooleanField(default=False)
    # Fechas por Sistema
    fecha_solicitud = models.DateField()

    def get_total_gs(self):
        if self.valor_compra_gs and self.comision_gs:
            return self.valor_compra_gs + self.comision_gs

    def get_total_dolar(self):
        if self.valor_compra_dolar and self.comision_dolar:
            return Decimal(self.valor_compra_dolar) + Decimal(self.comision_dolar)

    def get_saldo(self):
        pago_dolar = self.pago.filter(moneda__codigo='USD')
        pago_gs = self.pago.filter(moneda__codigo='Gs')
        cotizacion = Moneda.objects.get(codigo='USD').cotizacion
        if pago_dolar and pago_gs:  # Hubo pagos en Dolar y en Gs
            pago = pago_dolar.aggregate(dolar=Sum('monto'))
            pago_gs = pago_gs.aggregate(gs=Sum('monto'))
            pago['gs'] = pago_gs['gs']
            saldo = {'dolar': self.valor_compra_dolar + self.comision_dolar - pago['dolar'] - (pago['gs']/cotizacion)}
            saldo['gs'] = saldo['dolar'] * cotizacion
        elif pago_dolar:  # Hubo pagos en Dolar
            pago = pago_dolar.aggregate(dolar=Sum('monto'))
            saldo = {'dolar': self.valor_compra_dolar + self.comision_dolar - pago['dolar']}
            saldo['gs'] = saldo['dolar'] * cotizacion
        elif pago_gs:  # Hubo pagos en Gs
            pago = pago_gs.aggregate(gs=Sum('monto'))
            saldo = {'gs': self.valor_compra_gs + self.comision_gs - pago['gs']}
            saldo['dolar'] = saldo['gs'] / cotizacion
        return saldo

    def __unicode__(self):
        return "ID=%s de %s" % (self.id, self.user.get_full_name())

    class Meta:
        db_table = 'pytrade_compras'


class CompraDetalle(models.Model):
    ESTADO_COMPRA = (
        ('PC', 'Para Cotizar'),
        ('CZ', 'Cotizado'),
        ('P', 'Pagado'),
        ('C', 'Comprado')
    )
    # Por el Cliente cuando SOLICITA una Compra
    enlace = models.URLField(max_length=350)
    descripcion = models.CharField(max_length=200)
    comentario = models.TextField()
    # Por Admin cuando COTIZA una Compra
    valor_producto = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    valor_envio_interno = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    valor_impuesto = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    # Por Sistema cuando COTIZA una Compra
    valor_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank= True, null=True)  # Dolares (Total)
    valor_gs = models.BigIntegerField(blank=True, null=True)  # Guaranies (Total)
    # Por Admin cuando COMPLETA la Post Compra
    tracking = models.CharField(max_length=200, null=True, blank=True)
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True)
    # Por Sistema
    comprado = models.BooleanField(default=False)
    estado = models.CharField(max_length=50, choices=ESTADO_COMPRA)
    fecha_solicitud = models.DateField()
    fecha_compra = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return "CompraDetalle=%s - USD=%s - [%s]" % (self.id, self.valor_dolar, self.fecha_solicitud)

    class Meta:
        db_table = 'pytrade_compra_detalles'
        verbose_name_plural = "compras Detalles"


class Ubicacion(models.Model):
    nombre = models.CharField(max_length=20)
    codigo = models.CharField(max_length=15, null=True, blank=True)
    #fisica = models.BooleanField()

    def __unicode__(self):
        return "%s" % self.nombre

    class Meta:
        db_table = 'pytrade_ubicacion'
        verbose_name_plural = "ubicaciones"


class Paquete(models.Model):
    def url(self, filename):
        ruta = "MultimediaData/Paquetes/%s/%s" % (self.id, str(filename))
        return ruta
    # CSV en Origen (Miami)
    user = models.ForeignKey(User)
    codigo = models.CharField(max_length=70, null=True, blank=True)
    fecha = models.DateField(null=True, blank=True)
    descripcion = models.CharField(max_length=500)
    peso = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    tracking = models.CharField(max_length=200, null=True, blank=True)
    valor_dolar = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    # Por Personal de PyTrade
    ubicacion = models.ForeignKey('Ubicacion')
    entregado = models.BooleanField(default=False)
    costo_delivery = models.BigIntegerField(default=0)
    costo_seguro = models.BigIntegerField(default=0)
    # Guardo la cotizacion del dolar cuando se carga el CVS de Miami
    dolar = models.IntegerField()
    # Por Clientes
    seguro = models.BooleanField(default=False)
    valor_asegurado = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=0)
    factura = models.ImageField(upload_to=url, null=True, blank=True)
    delivery = models.BooleanField(default=False)
    sucursal = models.ForeignKey('home.Sucursal')
    # CSV en Asuncion
    fecha_destino = models.DateField(null=True, blank=True)
    # Operaciones
    # Monto del envio calculado por el Sistema al Cargar el CVS de Miami (En Gs y Dolar)
    costo_envio_gs = models.BigIntegerField(default=0)
    costo_envio_dolar = models.DecimalField(max_digits=12, decimal_places=2, null=True, default=0)
    # Sistema
    created_at = models.DateTimeField(db_column='fecha_creacion', auto_now_add=True)
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True)
    mail_origen = models.BooleanField(default=False)
    mail_destino = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s %s" % (self.user.username, self.descripcion)

    class Meta:
        db_table = 'pytrade_paquetes'


class Carga(models.Model):
    def path(self, filename):
        url = "reportes/%s/%s/%s/%s" % (self.origen, date.today().strftime('%Y'), date.today().strftime('%m'),  filename)
        return url
    origen = models.ForeignKey(Ubicacion)
    paquete = models.ManyToManyField(Paquete)
    archivo = models.FileField(upload_to=path)
    carga_asociada = models.ForeignKey('self', null=True, blank=True)
    cantidad_paquetes = models.IntegerField(null=True)
    kilo_carga = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    kilos = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.archivo.__str__()

    class Meta:
        db_table = 'pytrade_carga'


class Manifiesto(models.Model):
    fecha_arribo = models.DateField()
    origen = models.ForeignKey(Ubicacion)
    paquete = models.ManyToManyField(Paquete)
    bolsa_cantidad = models.IntegerField()
    bolsa_peso = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return "ID=%s - Bolsas=%s" % (self.id, self.bolsa_cantidad)

    class Meta:
        db_table = 'pytrade_manifiesto'


class Pago(models.Model):
    formapago = models.ForeignKey(FormaPago)  # Forma de Pago
    moneda = models.ForeignKey(Moneda, default=Moneda.objects.get(codigo='Gs'))  # Moneda de Pago
    monto = models.DecimalField(max_digits=30, decimal_places=2)
    created_at = models.DateTimeField(db_column='fecha', auto_now_add=True)

    def __unicode__(self):
        return "%s -> %s %s [%s]" % (self.id, self.monto, self.moneda.codigo, self.formapago.nombre)

    class Meta:

pytrade/templates/backend/compra_agregar.html
{%extends 'basebs.html' %}
{% load humanize %}
{% load bootstrap3 %}
{% block extra_head %}


{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>Agregar Órden de Compra. <small>Crear una Órden de Compra para un Cliente</small></h3>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-lg-10">
            <form action="" method="POST" class="form-horizontal">
                {% csrf_token %}

                <div class="row">
                    <div class="col-lg-6">  <!-- Seccion Datos Cliente -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">Datos del Cliente</div>
                            <div class="panel-body">
                                <!-- Avisos via JQuery -->
                                <div style="display: none" id="alertError">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="alert alert-danger" data-alert="alert">
                                                <button type="button" class="close" data-dismiss="alert">×</button>
                                                <p>No existe Cliente con ese Código. Editar el Código o <a href="{% url "vista_lista_clientes" %}" target="_blank">Buscar Clientes</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="col-md-4">
                                            {% bootstrap_field form.codigo_cliente layout='inline' %}
                                        </div>
                                        <div class="col-md-7" style="margin-left: 10px;">
                                            {% bootstrap_field form.nombre layout='inline' %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  <!-- FIN Seccion Datos Cliente -->
                </div> <!-- row -->
                <div class="row">
                    <div class="col-lg-12">  <!-- Seccion Datos de la Orden de Compra -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">Datos de la Órden de Compra</div>
                            <div class="panel-body">

                                <div class="panel panel-info">  <!-- Orden de Compra XX -->
                                    <div class="panel-heading">Órden de Compra <span id="cant_orden">1</span></div>
                                    <div class="panel-body">
                                        <div class="form-group" id="fields_wrapper">
                                            <div class="col-md-8">
                                                <div class="col-md-12">
                                                    {% bootstrap_field form.enlace layout='inline' %}
                                                </div>
                                                <div class="col-md-12">
                                                    {% bootstrap_field form.descripcion layout='inline' %}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="col-md-12">
                                                    {% bootstrap_field form.comentario layout='inline' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" id="botonera">
                                    <button type="button" class="btn btn-info" id="btn_agregar_orden">
                                        {% bootstrap_icon "plus" %} Agregar Órden de Compra
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>  <!-- FIN Seccion Datos de la Orden de Compra -->
                </div> <!-- row -->

                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "ok-circle" %} Guardar
                    </button>
                    <button type="submit" class="btn" name="_addanother">
                        {% bootstrap_icon "plus-sign" %} Guardar y agregar otro
                    </button>
                    <button type="submit" class="btn" name="_barcode">
                        {% bootstrap_icon "barcode" %} Generar Barcode
                    </button>
                    <button type="reset" class="btn">
                        {% bootstrap_icon "remove-circle" %} Limpiar
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div><!-- /.row -->
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $("#id_codigo_cliente").blur(function(){
            if ($(this).val()){
                $.ajax({
                    url : '/webservices/ws_codigo',
                    data: {'codigo_cliente' : $(this).val(), "csrfmiddlewaretoken": $('input[name=csrfmiddlewaretoken]').val()},
                    type : 'POST',
                    dataType : 'json',
                    success : function(datos) {
                        if (datos.response == 'nodata'){
                            $("#alertError").fadeIn();
                            $('#id_codigo_cliente').focus();

                        }else{
                            $('#id_nombre').val(datos);
                            $("#alertError").fadeOut();
                        }
                    },
                    error : function(jqXHR, status, error) {
                        alert('Disculpe, existió un problema. '+jqXHR.responseText);
                    }
                });
            }
        });

        $("#btn_agregar_orden").click(function(){
            var cant = $('.panel-info').size() + 1;
            var campos = '<div class="panel panel-info"><div class="panel-heading">Órden de Compra <span id="cant_orden">' + cant + '</span></div><div class="panel-body"><div id="fields_wrapper" class="form-group"><div class="col-md-8"><div class="col-md-12"><div class="form-group"><label class="None sr-only">Enlace</label><input type="text" title="" required="" placeholder="Enlace" name="enlace" maxlength="350" id="id_enlace" class="form-control"></div></div><div class="col-md-12"><div class="form-group"><label class="None sr-only">Descripcion</label><input type="text" title="" required="" placeholder="Descripcion" name="descripcion" maxlength="200" id="id_descripcion" class="form-control"></div></div></div><div class="col-md-4"><div class="col-md-12"><div class="form-group"><label class="None sr-only">Comentario</label><textarea title="" rows="5" required="" placeholder="Comentario" name="comentario" id="id_comentario" cols="40" class="form-control"></textarea></div></div></div></div></div></div>';
            $('#botonera').before(campos);
        });


        $("#btn_borrar_orden").click(function () {
            var cant = $('.fields_wrapper h3').size();

            if(cant==1){
                alert('No se puede borrar');
                return false;
            }

            $("#orden" + cant).remove();

        });
    </script>
{% endblock %}

pytrade/templates/backend/exportar_listado_mail.html
{% extends "basebs.html" %}
{% load bootstrap3 %}

{% block content %}
    <form method="GET" action="">
            <div class="row">
                <div class="span4">
                    <div class="input-control select">
                        {{ form }}
                    </div>
                </div>
            </div>
            <input type="submit" value="Exportar"/>
    </form>
{% endblock %}

pytrade/templates/backend/paquete_agregar_miami.html
{%extends 'basebs.html' %}
{% load humanize %}
{% load bootstrap3 %}
{% block extra_head %}


{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            {% if editar %}
                <h3>Editar Paquete.</h3>
            {% else %}
                <h3>Agregar Paquete. <small>Crear paquete en Origen</small></h3>
            {% endif %}
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-lg-10">
            <form action="" method="POST" class="form-horizontal">
                {% csrf_token %}

                <div class="row">
                    <div class="col-lg-5">  <!-- Seccion Datos Cliente -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">Datos del Cliente</div>
                            <div class="panel-body">
                                <!-- Avisos via JQuery -->
                                <div style="display: none" id="alertError">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="alert alert-danger" data-alert="alert">
                                                <button type="button" class="close" data-dismiss="alert">×</button>
                                                <p>No existe Cliente con ese Código. Editar el Código o <a href="{% url "vista_lista_clientes" %}" target="_blank">Buscar Clientes</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="col-md-4">
                                            {% bootstrap_field form.codigo_cliente layout='inline' %}
                                        </div>
                                        <div class="col-md-8">
                                            {% bootstrap_field form.nombre layout='inline' %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  <!-- FIN Seccion Datos Cliente -->
                </div>
                <div class="row">
                    <div class="col-lg-5">  <!-- Seccion Datos Paquetes -->
                        <div class="panel panel-info">
                            <div class="panel-heading">Datos del Paquete</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="col-md-3">
                                            {% bootstrap_field form.fecha layout='inline' %}
                                        </div>
                                        <div class="col-md-6">
                                            {% bootstrap_field form.ubicacion layout='inline' %}
                                        </div>
                                        <div class="col-md-3">
                                            {% bootstrap_field form.peso layout='inline' %}
                                        </div>
                                        <div class="col-md-7">
                                            {% bootstrap_field form.tracking layout='inline' %}
                                        </div>
                                        <div class="col-md-5">
                                            {% bootstrap_field form.proveedor layout='inline' %}
                                        </div>
                                        <div class="col-md-12">
                                            {% bootstrap_field form.descripcion layout='inline' %}
                                        </div>
                                        <div class="col-md-12">
                                            {% bootstrap_field form.codigo layout='inline' %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  <!-- FIN Seccion Datos Paquetes -->
                </div>

                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "ok-circle" %} Guardar
                    </button>
                    <button type="submit" class="btn" name="_addanother">
                        {% bootstrap_icon "plus-sign" %} Guardar y agregar otro
                    </button>
                    <button type="submit" class="btn" name="_barcode">
                        {% bootstrap_icon "barcode" %} Generar Barcode
                    </button>
                    <button type="reset" class="btn">
                        {% bootstrap_icon "remove-circle" %} Limpiar
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div><!-- /.row -->
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $("#id_codigo_cliente").blur(function(){
            if ($(this).val()){
                $.ajax({
                    url : '/webservices/ws_codigo',
                    data: {'codigo_cliente' : $(this).val(), "csrfmiddlewaretoken": $('input[name=csrfmiddlewaretoken]').val()},
                    type : 'POST',
                    dataType : 'json',
                    success : function(datos) {
                        if (datos.response == 'nodata'){
                            $("#alertError").fadeIn();
                            $('#id_codigo_cliente').focus();

                        }else{
                            $('#id_nombre').val(datos);
                            $("#alertError").fadeOut();
                        }
                    },
                    error : function(jqXHR, status, error) {
                        alert('Disculpe, existió un problema. '+jqXHR.responseText);
                    }
                });
            }
        });
    </script>
{% endblock %}