pytrade/apps/backend/urls.py
from django.conf.urls import patterns, url, include


urlpatterns = patterns(
    'pytrade.apps.backend.views',
    url(r'^$', 'index_view', name='vista_backend'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^exportar/$', 'paquete_exportar_view', name='vista_exportar_paquete'),
    url(r'^busqueda/(?P<tipo>.*)/$', 'cliente_busqueda_view', name='vista_busqueda_clientes'),
    url(r'^cliente/$', 'cliente_list_view', name='vista_lista_clientes'),
    url(r'^cliente/(?P<user>.*)/$', 'cliente_historial_view', name='vista_historial_cliente'),
    url(r'^paquete/$', 'paquete_list_view', name='vista_lista_paquetes'),
    url(r'^paquete/agrupar/$', 'paquete_agrupar_list', name='vista_agrupar_paquetes'),
    url(r'^paquete/agregar/$', 'paquete_agregar_view', name='vista_paquete_agregar'),
    url(r'^paquete/editar/(?P<id>.*)/$', 'paquete_editar_view', name='vista_paquete_editar'),
    url(r'^paquete/entregar/(?P<user>.*)/$', 'paquete_entregar_view', name='vista_entregar_paquete'),
    url(r'^paquete/wsentregar$', 'wspaquete_entregar_view', name='ws_entregar_paquete'),
    url(r'^mail/$', 'enviar_mail_view', name='vista_enviar_mail'),
    url(r'^compra/$', 'compra_list_view', name='vista_lista_compras'),
    url(r'^compra/agregar$', 'compra_agregar_view', name='vista_agregar_orden_compra'),
    url(r'^compra/cotizar/(?P<id>.*)/$', 'compra_cotizar_view', name='vista_cotizar_pedido'),
    url(r'^compra/pagar/(?P<id>.*)/$', 'compra_pagar_pedido_view', name='vista_pagar_pedido'),
    (r'^barcode/(?P<paquete>.*)/$', 'barcode_view'),
    url(r'^listado/$', 'generar_listado_mail_view', name='vista_generar_listado'),
    url(r'^carga/importar/$', 'carga_importar_view', name='vista_importar_carga'),
    url(r'^carga/$', 'carga_list_view', name='vista_lista_cargas'),
    url(r'^carga/(?P<id>.*)/$', 'carga_detalle_view', name='vista_detalle_carga'),
    url(r'^ticket/$', 'ticket_list_view', name='vista_lista_tickets'),
    url(r'^ticket/estado/$', 'ticket_cambio_estado_view', name='vista_cambio_estado_ticket'),
    url(r'^ticket/(?P<id>.*)/$', 'ticket_detalle_view', name='vista_detalle_ticket'),
    url(r'^proveedor/$', 'proveedor_abm_view', name='vista_agregar_proveedor'),
    url(r'^proveedor/(?P<id>.*)/$', 'proveedor_abm_view', name='vista_editar_proveedor'),
    #caja
    url(r'^caja/$', 'caja_list_view', name='vista_lista_caja'),
    url(r'^caja/apertura/$', 'caja_apertura_view', name='vista_apertura_caja'),
    url(r'^caja/egreso/$', 'caja_egreso_abm_view', name='vista_agregar_egreso'),
    url(r'^caja/abierta/$', 'caja_abierta_view', name='vista_caja_abierta'),
    url(r'^caja/cierre/(?P<id>.*)/$', 'caja_cierre_view', name='vista_cierre_caja'),
    url(r'^caja/(?P<id>.*)/$', 'caja_detalle_view', name='vista_detalle_caja'),
    #manifiesto
    url(r'^manifiesto/$', 'manifiesto_list_view', name='vista_lista_manifiesto'),
    url(r'^manifiesto/agregar$', 'manifiesto_agregar_view', name='vista_manifiesto_agregar'),
    url(r'^manifiesto/(?P<id>.*)/$', 'manifiesto_detalle_view', name='vista_detalle_manifiesto'),
    #factura
    url(r'^factura/(?P<factura_id>.*)/$', 'factura_detalle_view', name='vista_detalle_factura'),
    url(r'^facturacliente/(?P<ticket_id>.*)/$', 'factura_cliente_view', name='vista_factura_cliente'),
    #webservices
    url(r'^webservices/ws_motivo_egreso', 'wsmotivo_egreso_view', name='ws_motivo_egreso'),
    url(r'^webservices/ws_compra_divisa', 'wscompra_divisa_view', name='ws_compra_divisa'),
    url(r'^webservices/ws_detalle_compra_guardar', 'wsdetalle_compra_guardar_view', name='ws_guardar_detalle_compra'),
    url(r'^webservices/ws_ticket_estado', 'wsticket_cambio_estado_view', name='ws_ticket_cambio_estado'),
    url(r'^webservices/ws_manifiesto_paquetes', 'wsmanifiesto_paquetes_view', name='ws_manifiesto_paquetes'),
    url(r'^webservices/ws_cliente_factura', 'wsfactura_cliente_view', name='ws_manifiesto_paquetes'),
    #reportes
    url(r'^informe/1', 'i_cargas_cliente_view', name='i_cargas_cliente'),
    url(r'^informe/2', 'i_ingresos_egresos_view', name='i_ingresos_egresos'),
)

pytrade/apps/home/urls.py
from django.conf.urls import patterns, url
#from pytrade.apps.home.views import wsagregar_prepaquete
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = patterns(
    'pytrade.apps.home.views',
    url(r'^$', 'index_view', name='vista_inicio'),
    url(r'^login/', 'login_view', name='vista_login'),
    url(r'^logout/', 'logout_view', name='vista_logout'),
    url(r'^registrar/', 'registrar_view', name='vista_registrar'),
    # Perfiles
    url(r'^profile/$', 'profile_view', name='vista_profile'),
    url(r'^profile/edit/', 'perfil_usuario_view', name='vista_perfil'),
    url(r'^profile/comprar/', 'comprar_view', name='vista_comprar'),
    url(r'^profile/historial/', 'cliente_historial_view', name='vista_historial'),
    # Paginas Internas
    url(r'^empresa/', 'empresa_view', name='vista_empresa'),
    url(r'^servicio/', 'servicio_view', name='vista_servicio'),
    url(r'^tarifa/', 'tarifa_view', name='vista_tarifa'),
    url(r'^preguntas/', 'preguntas_view', name='vista_preguntas'),
    url(r'^tiendas/', 'tiendas_view', name='vista_tiendas'),
    url(r'^contacto/', 'contacto_view', name='vista_contacto'),
    #webservices
    url(r'^webservices/ws_email', 'wsemail_view', name='ws_email'),
    url(r'^webservices/ws_codigo', 'wscodigo_view', name='ws_codigo'),
    #RESTful
    #url(r'^ws/paquete/$', wsagregar_prepaquete.as_view(), name='vista_rest_agregar_prepaquete'),
)

#urlpatterns = format_suffix_patterns(urlpatterns)

pytrade/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('pytrade.apps.home.urls')),
    url(r'^backend/', include('pytrade.apps.backend.urls')),
    url(r'^recuperar/', include('password_reset.urls')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

#urlpatterns = format_suffix_patterns(urlpatterns)

pytrade/apps/backend/models.py
#encoding=utf8
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.db.models import Sum
from decimal import Decimal
#import django_filters


class Configuracion(models.Model):
    dolar = models.IntegerField()
    ultimo_valor = models.IntegerField()
    monto_minimo = models.IntegerField()
    comision = models.IntegerField(default=10)

    def __unicode__(self):
        return "Dolar=%s|Ult. Valor=%s|Monto=%s" % (self.dolar, self.ultimo_valor, self.monto_minimo)

    class Meta:
        db_table = 'pytrade_config'
        verbose_name_plural = "configuraciones"


class Moneda(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=10)
    cotizacion = models.IntegerField()

    def __unicode__(self):
        return self.codigo

    def natural_key(self):
        return self.codigo

    class Meta:
        db_table = 'pytrade_moneda'


# class Empresa(models.Model):
#     nombre = models.CharField(max_length=100)
#     codigo = models.CharField(max_length=100)
#     mail = models.EmailField(null=True, blank=True)
#
#     def __unicode__(self):
#         return "%s - %s" % (self.nombre, self.codigo)
#
#     class Meta:
#         db_table = 'pytrade_empresas'


class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    url = models.URLField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = 'pytrade_proveedor'
        verbose_name_plural = "proveedores"


class FormaPago(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=15)
    comision = models.IntegerField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = 'pytrade_formapago'


class Compra(models.Model):
    user = models.ForeignKey(User)
    detalle = models.ManyToManyField('CompraDetalle', blank=True, null=True)
    pago = models.ManyToManyField('Pago', blank=True, null=True)
    valor_compra_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)  # Suma Detalle Dolares
    valor_compra_gs = models.BigIntegerField(blank=True, null=True)  # Suma Detalle Guaranies
    comision_dolar = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Configuracion.comision/100
    comision_gs = models.BigIntegerField(null=True, blank=True)
    # Por Admin cuando el Cliente Paga Completamente
    pagado = models.BooleanField(default=False)
    # Fechas por Sistema
    fecha_solicitud = models.DateField()

    def get_total_gs(self):
        if self.valor_compra_gs and self.comision_gs:
            return self.valor_compra_gs + self.comision_gs

    def get_total_dolar(self):
        if self.valor_compra_dolar and self.comision_dolar:
            return Decimal(self.valor_compra_dolar) + Decimal(self.comision_dolar)

    def get_saldo(self):
        pago_dolar = self.pago.filter(moneda__codigo='USD')
        pago_gs = self.pago.filter(moneda__codigo='Gs')
        cotizacion = Moneda.objects.get(codigo='USD').cotizacion
        if pago_dolar and pago_gs:  # Hubo pagos en Dolar y en Gs
            pago = pago_dolar.aggregate(dolar=Sum('monto'))
            pago_gs = pago_gs.aggregate(gs=Sum('monto'))
            pago['gs'] = pago_gs['gs']
            saldo = {'dolar': self.valor_compra_dolar + self.comision_dolar - pago['dolar'] - (pago['gs']/cotizacion)}
            saldo['gs'] = saldo['dolar'] * cotizacion
        elif pago_dolar:  # Hubo pagos en Dolar
            pago = pago_dolar.aggregate(dolar=Sum('monto'))
            saldo = {'dolar': self.valor_compra_dolar + self.comision_dolar - pago['dolar']}
            saldo['gs'] = saldo['dolar'] * cotizacion
        elif pago_gs:  # Hubo pagos en Gs
            pago = pago_gs.aggregate(gs=Sum('monto'))
            saldo = {'gs': self.valor_compra_gs + self.comision_gs - pago['gs']}
            saldo['dolar'] = saldo['gs'] / cotizacion
        return saldo

    def __unicode__(self):
        return "ID=%s de %s" % (self.id, self.user.get_full_name())

    class Meta:
        db_table = 'pytrade_compras'


class CompraDetalle(models.Model):
    ESTADO_COMPRA = (
        ('PC', 'Para Cotizar'),
        ('CZ', 'Cotizado'),
        ('P', 'Pagado'),
        ('C', 'Comprado')
    )
    # Por el Cliente cuando SOLICITA una Compra
    enlace = models.URLField(max_length=350)
    descripcion = models.CharField(max_length=200)
    comentario = models.TextField()
    # Por Admin cuando COTIZA una Compra
    valor_producto = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    valor_envio_interno = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    valor_impuesto = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Dolares
    # Por Sistema cuando COTIZA una Compra
    valor_dolar = models.DecimalField(max_digits=10, decimal_places=2, blank= True, null=True)  # Dolares (Total)
    valor_gs = models.BigIntegerField(blank=True, null=True)  # Guaranies (Total)
    # Por Admin cuando COMPLETA la Post Compra
    tracking = models.CharField(max_length=200, null=True, blank=True)
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True)
    # Por Sistema
    comprado = models.BooleanField(default=False)
    estado = models.CharField(max_length=50, choices=ESTADO_COMPRA)
    fecha_solicitud = models.DateField()
    fecha_compra = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return "CompraDetalle=%s - USD=%s - [%s]" % (self.id, self.valor_dolar, self.fecha_solicitud)

    class Meta:
        db_table = 'pytrade_compra_detalles'
        verbose_name_plural = "compras Detalles"


class Ubicacion(models.Model):
    nombre = models.CharField(max_length=20)
    codigo = models.CharField(max_length=15, null=True, blank=True)
    #fisica = models.BooleanField()

    def __unicode__(self):
        return "%s" % self.nombre

    class Meta:
        db_table = 'pytrade_ubicacion'
        verbose_name_plural = "ubicaciones"


class Paquete(models.Model):
    def url(self, filename):
        ruta = "MultimediaData/Paquetes/%s/%s" % (self.id, str(filename))
        return ruta
    # CSV en Origen (Miami)
    user = models.ForeignKey(User)
    codigo = models.CharField(max_length=70, null=True, blank=True)
    fecha = models.DateField(null=True, blank=True)
    descripcion = models.CharField(max_length=500)
    peso = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    tracking = models.CharField(max_length=200, null=True, blank=True)
    valor_dolar = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    # Por Personal de PyTrade
    ubicacion = models.ForeignKey('Ubicacion')
    entregado = models.BooleanField(default=False)
    costo_delivery = models.BigIntegerField(default=0)
    costo_seguro = models.BigIntegerField(default=0)
    # Guardo la cotizacion del dolar cuando se carga el CVS de Miami
    dolar = models.IntegerField()
    # Por Clientes
    seguro = models.BooleanField(default=False)
    valor_asegurado = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=0)
    factura = models.ImageField(upload_to=url, null=True, blank=True)
    delivery = models.BooleanField(default=False)
    sucursal = models.ForeignKey('home.Sucursal')
    # CSV en Asuncion
    fecha_destino = models.DateField(null=True, blank=True)
    # Operaciones
    # Monto del envio calculado por el Sistema al Cargar el CVS de Miami (En Gs y Dolar)
    costo_envio_gs = models.BigIntegerField(default=0)
    costo_envio_dolar = models.DecimalField(max_digits=12, decimal_places=2, null=True, default=0)
    # Sistema
    created_at = models.DateTimeField(db_column='fecha_creacion', auto_now_add=True)
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True)
    mail_origen = models.BooleanField(default=False)
    mail_destino = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s %s" % (self.user.username, self.descripcion)

    class Meta:
        db_table = 'pytrade_paquetes'


class Carga(models.Model):
    def path(self, filename):
        url = "reportes/%s/%s/%s/%s" % (self.origen, date.today().strftime('%Y'), date.today().strftime('%m'),  filename)
        return url
    origen = models.ForeignKey(Ubicacion)
    paquete = models.ManyToManyField(Paquete)
    archivo = models.FileField(upload_to=path)
    carga_asociada = models.ForeignKey('self', null=True, blank=True)
    cantidad_paquetes = models.IntegerField(null=True)
    kilo_carga = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    kilos = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.archivo.__str__()

    class Meta:
        db_table = 'pytrade_carga'


class Manifiesto(models.Model):
    fecha_arribo = models.DateField()
    origen = models.ForeignKey(Ubicacion)
    paquete = models.ManyToManyField(Paquete)
    bolsa_cantidad = models.IntegerField()
    bolsa_peso = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return "ID=%s - Bolsas=%s" % (self.id, self.bolsa_cantidad)

    class Meta:
        db_table = 'pytrade_manifiesto'


class Pago(models.Model):
    formapago = models.ForeignKey(FormaPago)  # Forma de Pago
    moneda = models.ForeignKey(Moneda, default=Moneda.objects.get(codigo='Gs'))  # Moneda de Pago
    monto = models.DecimalField(max_digits=30, decimal_places=2)
    created_at = models.DateTimeField(db_column='fecha', auto_now_add=True)

    def __unicode__(self):
        return "%s -> %s %s [%s]" % (self.id, self.monto, self.moneda.codigo, self.formapago.nombre)

    class Meta:

pytrade/templates/home/comprar.html
{% extends "base_lateral.html" %}


{% block content-int %}
<div class="contact twelve columns">
    <div class="standard-form compressed">
        <h4 class="semi">Compramos por Vos</h4>
        <p>Si no posees una Tarjeta de Crédito y/o no quieres utilizar la que tienes, utiliza nuestro servicio <strong>"Compramos por Vos".</strong></p>
        <p>Le recordamos que contamos con cuenta de PayPal, por lo que tus compras en <a href="http://www.ebay.com/">eBay</a> son posibles.</p>
        <p><h5>El costo de este servicio es de 10% del valor total de la Orden de Compra.</h5></p>
        <p><strong>¿Cómo funciona?</strong></p>
        <ol>
            <li style="margin-bottom: 4px;">Seleccionar el producto deseado a través de alguna tienda virtual.</li>
            <li style="margin-bottom: 4px;">Copiar el enlace o URL de la página web y pegar en el campo Enlace de esta página.</li>
            <li style="margin-bottom: 4px;">Es obligatorio completar la <strong>descripción corta</strong> (Reloj, Billetera, Electronica, etc) y un <strong>comentario sobre el producto</strong> (color, medida, modelo, etc).</li>
            <li style="margin-bottom: 4px;">Pasar por nuestra oficina y abonar el 100% del costo total de la Orden de Compra.</li>
            <li style="margin-bottom: 4px;">Al retirar el producto, se abonará el costo del envío.</li>
        </ol>
        {% if error %}
            <div class="form-result">
                <p class="note error">{{ error }}</p>
            </div>
        {% endif %}

        <form action="" id="registro" method="POST">
            {% csrf_token %}
            <div class="fields_wrapper">
                <div id="orden1">
                    <h3>Orden de Compra <span id="cant_orden">1</span></h3>
                    {{ form.enlace }}
                    {{ form.descripcion }}
                    {{ form.comentario }}
                </div>
            </div>
            <button type="button" class="btn" id="btn_agregar_orden">Agregar Orden</button>
            <button type="button" class="btn btn-default" id="btn_borrar_orden">Eliminar Orden</button>
            <div class="submit">
                <button type="submit" class="btn-orange" >Solicitar Compra</button>
            </div>
        </form>
        <div class="clear"></div>
    </div>
</div>
    <script type="text/javascript">
        $("#btn_agregar_orden").click(function(){
            var cant = $('.fields_wrapper h3').size() + 1;
            var campos = '<div id="orden'+ cant +'"><div class="orden"><h3>Orden de Compra <span id="cant_orden">' + cant + '</span></h3></div><input type="text" name="enlace" maxlength="350" id="id_enlace"> <input type="text" name="descripcion" maxlength="200" id="id_descripcion"> <textarea rows="10" name="comentario" id="id_comentario" cols="40"></textarea></div>';
            $('.fields_wrapper').append(campos);

        });


        $("#btn_borrar_orden").click(function () {
            var cant = $('.fields_wrapper h3').size();

            if(cant==1){
                alert('No se puede borrar');
                return false;
            }

            $("#orden" + cant).remove();

        });
    </script>
{% endblock %}

pytrade/templates/home/contacto.html
{% extends "base_lateral.html" %}

{% block content-int %}
    <div class="sixteen map columns">
        <iframe width="100%" height="260px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.py/maps?q=PyTrade&amp;hl=es&amp;sll=-25.282983,-57.576299&amp;sspn=0.016511,0.033023&amp;hq=PyTrade&amp;t=m&amp;ie=UTF8&amp;hnear=&amp;cid=5736821408188523643&amp;ll=-25.279859,-57.571707&amp;spn=0.009313,0.008497&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
    </div>
    <div class="sixteen columns"><span class="hr mapdv" style="margin: 0 0 10px;"></span></div>
    <div class="contact twelve columns">
        <div class="standard-form compressed">
            <h4 class="semi">Contáctenos</h4>
            <div class="form-result"></div>
            <form action="#" class="contactForm" id="contactus" name="contacto">
            <input type="text" class="input" id="name" name="name" placeholder="Nombre">
            <input type="text" class="input" id="email" name="name" placeholder="Email">
            <input type="text" class="input extend" id="email" name="name" placeholder="Asunto">
            <textarea name="comment" id="comment" rows="10" cols="65" placeholder="Mensaje"></textarea>
                <div class="submit">
                    <a href="#" class="button color"><span>Enviar</span></a>
                </div>
                <div class="clear"></div>
            </form>
        </div>
    </div>
{% endblock %}

pytrade/templates/home/empresa.html
{% extends "base_lateral.html" %}

{% block content-int %}
<div class="twelve columns">
    <div class="sidebar-right"><br /><br />
        <h5 class="title">¿Quiénes Somos?</h5>
        <blockquote class="full">
            Somos una empresa de Courier y Transporte Internacional de cargas, vía marítima y aérea, que dedica toda su energía en brindar la mejor atención y servicio al cliente.<br />
            Comprendemos la importancia de todos y cada uno de los deseos de nuestros clientes, por lo que sumamos eficacia y seguridad, junto al mejor precio,
            desde el momento en el que su paquete llega a nosotros, hasta que lo entregamos en sus manos.
        </blockquote>
        <div id="nosotros-mision">
            <h3>Misión</h3>
            <p style="text-align: justify">
                Es nuestra misión poder ofrecer un servicio de envíos puerta a puerta, por medio aéreo, con precios accesibles, tiempos rápidos y total seguridad donde el cliente
                pueda confiar en nuestro servicio. Buscamos a la vez ser socios de nuestros clientes, haciéndoles parte de nuestro crecimiento comercial y abriendo las puertas a
                las sugerencias y comentarios que nos puedan hacer mejorar cada vez más.
            </p>
        </div>
        <div id="nosotros-vision">
            <h3>Visión</h3>
            <p style="text-align: justify">
                Nuestra visión es la de una empresa multinacional interconectada entre sus diferentes agencias en puntos claves del mundo ofreciendo servicio de courier,
                importación y exportación vía aérea y marítima con costos accesibles, tiempos rápidos y máxima confiabilidad para su empresa o uso particular.
            </p>
        </div>
    </div>
</div>
{% endblock %}

pytrade/templates/home/index.html
{% extends "base.html" %}
{% load url from future %}

pytrade/templates/home/login.html
{% extends "base_lateral.html" %}

{% block content-int %}
<div class="contact twelve columns">
    <div class="standard-form compressed">
        <h4 class="semi">Ingresa a tu cuenta PyTrade</h4>
        <div class="sociaLogin">
            <a id="facebook-login" href="{% url 'social:begin' "facebook" %}" class="btn-auth btn-facebook large">Login con Facebook</a><br />
        </div>

        <br />
        <h3 class="semi">- O -</h3>

        {% if error %}
            <div class="form-result">
                <p class="note error">{{ error }}</p>
            </div>
        {% endif %}
        <form action="" id="registro" method="POST" style="margin-bottom:40%;">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <div class="submit">
                <button type="submit" class="btn-orange" >Ingresar</button>
            </div>
            <h5><a href="{% url "password_reset_recover" %}">¿Olvidaste tu contraseña?</a></h5>
        </form>
        <div class="clear"></div>
    </div>
</div>
{% endblock %}

pytrade/templates/home/profile.html
{% extends "base_lateral.html" %}

{% block content-int %}
<div class="twelve columns">
    <div class="sidebar-right">
        <h4 class="semi">Perfil PyTrade</h4>
        {% if msj == 1 %}
            <div class="form-result">
                <p class="note success">Gracias por registrarte a PyTrade.</p>
                <p class="note warning">A continuación debe completar los siguientes datos para crear su Casilla de Correo.</p>
            </div>
        {% elif msj == 2 %}
            <div class="form-result">
                <p class="note warning">Completa tus datos</p>
            </div>
        {% elif msj == 3 %}
            <div class="form-result">
                <p class="note success">Datos actualizados correctamente</p>
            </div>
        {% endif %}

        {% if messages %}
            {% for m in messages %}
                <div class="form-result">
                    <p class="note {{ m.tags }}">{{ m }}</p>
                </div>
            {% endfor %}
        {% endif %}


        <h5 class="semi">
            Bienvenido {{ user.first_name }} {{ user.last_name }} -
            <a href="{% url 'vista_perfil'%}">Editar Perfil</a>
        </h5>
        <h5 class="semi">
            Compramos por vos <a href="{% url 'vista_comprar'%}">Comprar</a>
        </h5>
        {% if compras %}
            <h5 class="semi">Compras Pendientes</h5>
            <div class="tabla">
                <table>
                    <tr>
                        <td>ID</td>
                        <td>Fecha Solicitud</td>
                        <td>Estado</td>
                        <td>Enlace</td>
                    </tr>
                    {% for c in compras %}
                        {% for d in c.detalle.all %}
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.fecha_solicitud }}</td>
                                <td>{{ d.get_estado_display }}</td>
                                <td>{{ d.enlace|truncatechars:35 }}</td>
                            </tr>
                        {% endfor %}

                    {% endfor %}
                </table>
            </div>
            <br /><br />
        {% else %}
            <h5 class="semi">No hay compras pendientes</h5>
        {% endif %}
        {% if paquetes %}
            <h5 class="semi">Paquetes Pendientes</h5>
            <div class="tabla">
                <table>
                    <tr>
                        <td>ID</td>
                        <td>Fecha</td>
                        <td>Descripción</td>
                        <td>Tracking</td>
                        <td>Peso</td>
                        <td>Estado</td>
                    </tr>
                    {% for p in paquetes %}
                        <tr>
                            <td>{{ p.id }}</td>
                            <td>{{ p.fecha }}</td>
                            <td>{{ p.descripcion }}</td>
                            <td>{{ p.tracking }}</td>
                            <td>{{ p.peso }} Kg.</td>
                            <td>{{ p.ubicacion }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <br /><br />
        {% else %}
            <h5 class="semi">No hay paquetes pendientes</h5>
        {% endif %}

        <h5 class="semi" style="margin-top: 5px;">Historial de Paquetes y Compras. <a href="{% url 'vista_historial' %}">Ver</a> </h5>
    </div>
</div>
{% endblock %}